@startuml

scale 1.0

skinparam monochrome true
skinparam RectangleBackgroundColor white

rectangle class [
methods of the Class<T> class
]

rectangle primitives [
method for primitives
--
boolean isPrimitive()
]

rectangle arrays [
methods for arrays
--
boolean isArray()
<color:#gray>Class<?> getComponentType()
Class<?> componentType()
Class<?> arrayType()
]

rectangle modifiers [
methods for modifiers
--
int getModifiers()
..
boolean isInterface()
boolean isArray()
boolean isPrimitive()
boolean isAnnotation()
boolean isSynthetic()
boolean isAnonymousClass()
boolean isLocalClass()
boolean isMemberClass()
boolean isEnum()
boolean isRecord()
boolean isHidden()
boolean isSealed()
]

rectangle inheritance [
methods for inheritance
--
Class<? super T> getSuperclass()
Class<?>[] getInterfaces()
..
boolean isInstance(Object obj)
boolean isAssignableFrom(Class<?> cls)
..
T cast(Object obj)
Class<? extends U> asSubclass(Class~<U> cls)
]

rectangle nested_classes [
methods for nested classes
--
boolean isAnonymousClass()
boolean isLocalClass()
boolean isMemberClass()
..
Class<?>[] getClasses()
Class<?>[] getDeclaredClasses()
..
Method getEnclosingMethod()
Constructor<?> getEnclosingConstructor()
Class<?> getEnclosingClass()
Class<?> getDeclaringClass()
..
Class<?> getNestHost()
boolean isNestmateOf(Class<?> cls)
Class<?>[] getNestMembers()
]

rectangle restricted_classes [
methods for restricted classes
--
boolean isEnum()
T[] getEnumConstants()
..
boolean isRecord()
RecordComponent[] getRecordComponents()
..
boolean isSealed()
Class<?>[] getPermittedSubclasses()
]

class -down- primitives
class -down- arrays
class -down-- modifiers
class -down- inheritance
class -down-- nested_classes
class -down- restricted_classes

@enduml