@startuml

skinparam RectangleBackgroundColor white
skinparam RectangleBorderColor black
skinparam RectangleFontName Source Sans Pro
skinparam RectangleFontSize 16
skinparam ArrowColor black

rectangle class [
methods of the Array class
]

rectangle methods1 [
method for determining the length of arrays
--
int getLength(Object array)
]

rectangle methods2 [
arrays' getters and setters
--
Object get(Object array, int index)
boolean getBoolean(Object array, int index)
byte getByte(Object array, int index)
char getChar(Object array, int index)
short getShort(Object array, int index)
int getInt(Object array, int index)
long getLong(Object array, int index)
float getFloat(Object array, int index)
double getDouble(Object array, int index)
..
void set(Object array, int index, Object value)
void setBoolean(Object array, int index, boolean value)
void setByte(Object array, int index, byte value)
void setChar(Object array, int index, char value)
void setShort(Object array, int index, short value)
void setInt(Object array, int index, int value)
void setLong(Object array, int index, long value)
void setFloat(Object array, int index, float value)
void setDouble(Object array, int index, double value)
]

rectangle methods3 [
methods for creating arrays
--
Object newInstance(Class<?> componentType, int length)
Object newInstance(Class<?> componentType, int... dimensions)
]

class -down- methods1
class -down-- methods2
class -down- methods3

@enduml