@startuml

skinparam RectangleBackgroundColor white
skinparam RectangleBorderColor black
skinparam RectangleFontName Source Sans Pro
skinparam RectangleFontSize 16
skinparam ArrowColor black

rectangle class [
methods of the Modifier class
]

rectangle methods1 [
methods for determining individual modifiers
--
boolean isPublic(int)
boolean isPrivate(int)
boolean isProtected(int)
boolean isStatic(int)
boolean isFinal(int)
boolean isSynchronized(int)
boolean isVolatile(int)
boolean isTransient(int)
boolean isNative(int)
boolean isInterface(int)
boolean isAbstract(int)
boolean isStrict(int)
]

rectangle methods2 [
methods for determining all applicable modifiers
--
int classModifiers()
int interfaceModifiers()
int fieldModifiers()
int methodModifiers()
int constructorModifiers()
int parameterModifiers()
]

class -down- methods1
class -down- methods2

@enduml